config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # GET /about
  get "about", to: "about#index", as: "about"

  get "password", to: "password#edit", as: "edit_password"
  patch "password", to: "password#update"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"

  delete "logout", to: "session#destroy"

  get "auth/twitter/callback", to: "omniauth_callback#twitter"

  resources :twitter_account
  resources :tweets

  root to: "main#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do 
    self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets

  has_secure_password

  accepts_nested_attributes_for :twitter_accounts

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callback_controller.rb
class OmniauthCallbackController < ApplicationController
  def twitter
    twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    twitter_account.update(
      name: auth.info.name,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret,
    )

    redirect_to twitter_account_index_path, notice: "Successfully connected your account"
  end


  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated!"
    else
      render :edit
    end
  end

  private

  def password_params
    params.required(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver_now
    end

    redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password."
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
    else
      render :edit
    end
    
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  
    # def index
    #   @ = .scoped
    # end
  
    def new
      @user = User.new()
    end

    def create
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Successfully created account"
      else
        render :new
      end
    end
  
    # def update
    #   @ = .find(params[:id])
    # end
  
    # def edit
    #   @ = .find(params[:id])
    # end
  
    # def destroy
    #   @ = .find(params[:id])
    # end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    if session[:user_id]
      session[:user_id] = nil
    end

    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.create(tweet_params)

    if @tweet.save
      redirect_to tweets_path, notice: "Tweet was scheduled successfully"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Tweet was updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet was unscheduled successfully"
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/controllers/twitter_account_controller.rb
class TwitterAccountController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end

  def destroy
    @twitter_accounts.destroy

    redirect_to twitter_account_index_path, notice: "Successfully disconnected @#{@twitter_accounts.username}"
  end

  private

  def set_twitter_account
    @twitter_accounts = Current.user.twitter_accounts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>

    <div class="container">
      <%= render partial: "shared/flash"%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to Scheduled Tweets</h1>
</div>

<% if Current.user %>
  <%= button_to "Connect Twitter", "/auth/twitter", method: :post, data: {turbo: "false"}, class: "btn btn-primary" %>
<% end %>

app/views/password/edit.html.erb
<h1>Edit Password</h1>

<%= form_with model: Current.user, url: edit_password_path, data: {turbo: false}  do |form| %>
  <%= render 'shared/form_errors', form: form %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password , class: "form-control", placeholder: "password"%>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation , class: "form-control" , placeholder: "password"%>
  </div>

  <div class="mb-3">
    <%= form.submit "Sign up", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_reset/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), data: {turbo: false} do |form| %>
  <%= render 'shared/form_errors', form: form %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password , class: "form-control", placeholder: "password"%>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation , class: "form-control" , placeholder: "password"%>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_reset/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path, data: {turbo: false} do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "steve@apple.com" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/session/new.html.erb
<h1>Sign In</h1>

<%= form_with url: sign_in_path, data: {turbo: false} do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "steve@apple.com" %>
  </div>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password , class: "form-control", placeholder: "password"%>
    <%= link_to "Forgot your password?", password_reset_path %>
  </div>

  <div class="mb-3">
    <%= form.submit "Sign Up", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4">
    <%= flash[:alert] %>
  </div>

<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_account_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: tweet, data: {turbo: false} do |form| %>
  <%= render 'shared/form_errors', form: form %>

  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control" } %>
    <%= link_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: { turbo: "false" } %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_at %>
    <div class="form-control">
      <%= form.datetime_select :publish_at %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit "Schedule", class: "btn btn-primary" %>

    <% if form.object.persisted? %>
      <%= link_to "Delete", form.object, method: :delete, data: { turbo: "false", confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
    <% end %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
  <%= tweet.body %>

  <div class="me-4">
    <%= image_tag tweet.twitter_account.image, class: "rounded-circle" %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>
  </div>

  <% if tweet.published? %>
    <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
  <% else %>
    Scheduled for <%= l tweet.publish_at, format: :long %>
    <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<h1>Schedule A Tweet</h1>

<%= render 'form', tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-centers">
  <h1>Tweets</h1>

  <% if Current.user.twitter_accounts.any? %>
    <%= button_to "Schedule a Tweet", new_tweet_path, method: :get, data: { turbo: "false" }, class: "btn btn-primary" %>
  <% end %>

  <% if Current.user.twitter_accounts.none? %>
    <%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: { turbo: "false" }, class: "btn btn-primary" %>
  <% end %>
</div>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%= render 'form', tweet: @tweet %>

app/views/twitter_account/index.html.erb
<div class="d-flex align-items-center justify-content-between">
  <h1>Twitter Accounts</h1>
  <%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: { turbo: "false" }, class: "btn btn-primary" %>
</div>



<% @twitter_accounts.each do |twitter_account| %>
  <div class="d-flex align-items-center mb-4">
    <div class="me-4">
      <%= image_tag twitter_account.image, class: "rounded-circle" %>
      <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
    </div>

    <%= button_to "Disconnect", twitter_account, method: :delete, data: { confirm: "Are you sure?", turbo: "false" }, class: "btn btn-secondary" %>
  </div>
<% end %>